name = "HydroTools"
uuid = "179359cd-bac3-4aa1-bccd-287172463ab0"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extensions]
MetPyExt = "PyCall"

[compat]
julia = "1.9"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
